#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"

#########################################################

WALLPAPERS="${HOME}/.media/img/wallpapers/"
OPTIONS_FILE="$WALLPAPERS/options"
VIEWER="/usr/local/bin/xli"
OPT="-onroot -border black"
#POWER_SAVE="on"
##
## Set background
##
case $POWER_SAVE in
    on) bsetroot -solid black;;
    *)
        IMG=`cd $WALLPAPERS; ls *.jpg *.gif | sort -R | head -n 1`;
        OPTIONS=`grep $IMG $OPTIONS_FILE`;

        if (test -z "$OPTIONS");
        then
            OPT="$OPT -fullscreen $WALLPAPERS/$IMG";
        else
            OPT="$OPT `echo "$OPTIONS" | cut -c 20-100` $WALLPAPERS/$IMG"
        fi

        echo "$OPT" | xargs $VIEWER ;;
esac


##
## Load settings
##
xrdb ~/.Xresources


##
## Exec xterm
##
#koi8rxterm &
uxterm &


##
## Video
##
#nvidia-settings --load-config-only
#xrandr --output LVDS1 --brightness 0.7 --output VGA1 --right-of LVDS1

##
## Keyboard / Mouse
##
#xmodmap -e "keysym Menu = Pointer_Button1"
#xmodmap -e "keysym Insert = Pointer_Button2"
#xmodmap -e "keysym Control_R = Pointer_Button3"
#xkbset mousekeys
xset -b

exec fluxbox
